[package]
name = "pyo3-levenshtein"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.27.1", features = ["abi3-py310"] }

[lib]
name = "pyo3_levenshtein"
crate-type = ["cdylib"]
